// lib/constants.ts
export const NavLinks = {
  Home: "/",
  About: "/about",
  Katalog: "/katalog",
  Product: "/highlight",
  Kontak: "/contact",
  Membership: "/membership",
};

export type NavLinkKey = keyof typeof NavLinks;

export const SocialLinks = {
  instagram: "https://instagram.com/rainygurlll_/",
  whatsapp: "https://wa.me/0812345678", // Still placeholder
  tiktok: "https://tiktok.com/@rainygurlll_",
  shopee: "https://shopee.co.id/rainygurlll.official",
};

export const PageRoutes = {
  penjualan: "/penjualan",
  formMember: "/form-member",
};

// Product Categories
export const ProductCategories = {
  tops: "Atasan",
  bottoms: "Bawahan",
  dresses: "Dress",
  accessories: "Aksesoris",
  shoes: "Sepatu",
};

// Product Filters
export const ProductFilters = {
  price: {
    all: "Semua Harga",
    under50k: "Di bawah 50k",
    "50k-100k": "50k - 100k",
    "100k-200k": "100k - 200k",
    above200k: "Di atas 200k",
  },
  size: {
    all: "Semua Ukuran",
    xs: "XS",
    s: "S",
    m: "M",
    l: "L",
    xl: "XL",
    xxl: "XXL",
  },
  color: {
    all: "Semua Warna",
    black: "Hitam",
    white: "Putih",
    red: "Merah",
    blue: "Biru",
    green: "Hijau",
    pink: "Pink",
    brown: "Coklat",
  },
};

// Product Badge Types
export const ProductBadges = {
  hottest: "hottest",
  sale: "sale",
};

// Mock Products Data
export const MockProducts = [
  // Hottest Products (prioritas tertinggi)
  {
    id: 1,
    name: "Crop Top Vintage",
    price: 89000,
    originalPrice: 89000,
    category: "tops",
    image: "https://placehold.co/300x400/ff6b9d/ffffff?text=Crop+Top",
    badge: ProductBadges.hottest,
    sizes: ["S", "M", "L"],
    colors: ["black", "white", "pink"],
    description: "Crop top dengan desain vintage yang trendy",
    stock: 15,
  },
  {
    id: 2,
    name: "High Waist Jeans",
    price: 159000,
    originalPrice: 159000,
    category: "bottoms",
    image: "https://placehold.co/300x400/4ecdc4/ffffff?text=High+Waist+Jeans",
    badge: ProductBadges.hottest,
    sizes: ["S", "M", "L", "XL"],
    colors: ["blue", "black"],
    description: "Jeans high waist yang nyaman dan stylish",
    stock: 8,
  },
  {
    id: 3,
    name: "Floral Dress",
    price: 199000,
    originalPrice: 199000,
    category: "dresses",
    image: "https://placehold.co/300x400/ffe66d/ffffff?text=Floral+Dress",
    badge: ProductBadges.hottest,
    sizes: ["S", "M", "L"],
    colors: ["pink", "white", "green"],
    description: "Dress floral yang cantik untuk berbagai acara",
    stock: 12,
  },

  // Sale Products (prioritas kedua)
  {
    id: 4,
    name: "Oversized Hoodie",
    price: 119000,
    originalPrice: 149000,
    category: "tops",
    image: "https://placehold.co/300x400/a8e6cf/ffffff?text=Oversized+Hoodie",
    badge: ProductBadges.sale,
    discount: 20,
    sizes: ["M", "L", "XL"],
    colors: ["black", "white", "brown"],
    description: "Hoodie oversized yang hangat dan nyaman",
    stock: 20,
  },
  {
    id: 5,
    name: "Mini Skirt",
    price: 69000,
    originalPrice: 89000,
    category: "bottoms",
    image: "https://placehold.co/300x400/ffd93d/ffffff?text=Mini+Skirt",
    badge: ProductBadges.sale,
    discount: 22,
    sizes: ["XS", "S", "M"],
    colors: ["black", "red", "blue"],
    description: "Mini skirt yang cute dan versatile",
    stock: 25,
  },
  {
    id: 6,
    name: "Statement Earrings",
    price: 39000,
    originalPrice: 59000,
    category: "accessories",
    image: "https://placehold.co/300x400/ff9ff3/ffffff?text=Statement+Earrings",
    badge: ProductBadges.sale,
    discount: 34,
    sizes: ["all"],
    colors: ["all"],
    description: "Anting statement yang eye-catching",
    stock: 30,
  },

  // Regular Products
  {
    id: 7,
    name: "Basic T-Shirt",
    price: 49000,
    originalPrice: 49000,
    category: "tops",
    image: "https://placehold.co/300x400/6c5ce7/ffffff?text=Basic+T-Shirt",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["black", "white", "red", "blue"],
    description: "T-shirt basic yang wajib dimiliki",
    stock: 50,
  },
  {
    id: 8,
    name: "Pleated Skirt",
    price: 99000,
    originalPrice: 99000,
    category: "bottoms",
    image: "https://placehold.co/300x400/fd79a8/ffffff?text=Pleated+Skirt",
    sizes: ["S", "M", "L"],
    colors: ["black", "white", "pink"],
    description: "Rok pleated yang elegan dan feminin",
    stock: 18,
  },
  {
    id: 9,
    name: "Maxi Dress",
    price: 229000,
    originalPrice: 229000,
    category: "dresses",
    image: "https://placehold.co/300x400/00b894/ffffff?text=Maxi+Dress",
    sizes: ["S", "M", "L", "XL"],
    colors: ["green", "blue", "brown"],
    description: "Maxi dress yang elegan untuk acara formal",
    stock: 10,
  },
  {
    id: 10,
    name: "Canvas Sneakers",
    price: 179000,
    originalPrice: 179000,
    category: "shoes",
    image: "https://placehold.co/300x400/fdcb6e/ffffff?text=Canvas+Sneakers",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["white", "black", "pink"],
    description: "Sneakers canvas yang nyaman untuk daily wear",
    stock: 22,
  },
  {
    id: 11,
    name: "Crossbody Bag",
    price: 129000,
    originalPrice: 129000,
    category: "accessories",
    image: "https://placehold.co/300x400/e17055/ffffff?text=Crossbody+Bag",
    sizes: ["all"],
    colors: ["black", "brown", "white"],
    description: "Tas crossbody yang praktis dan stylish",
    stock: 15,
  },
  {
    id: 12,
    name: "Denim Jacket",
    price: 189000,
    originalPrice: 189000,
    category: "tops",
    image: "https://placehold.co/300x400/74b9ff/ffffff?text=Denim+Jacket",
    sizes: ["S", "M", "L", "XL"],
    colors: ["blue", "black"],
    description: "Jaket denim klasik yang timeless",
    stock: 12,
  },
  {
    id: 13,
    name: "Wide Leg Pants",
    price: 139000,
    originalPrice: 139000,
    category: "bottoms",
    image: "https://placehold.co/300x400/55a3ff/ffffff?text=Wide+Leg+Pants",
    sizes: ["S", "M", "L"],
    colors: ["black", "brown", "blue"],
    description: "Celana wide leg yang trendy dan comfortable",
    stock: 16,
  },
  {
    id: 14,
    name: "Midi Dress",
    price: 169000,
    originalPrice: 169000,
    category: "dresses",
    image: "https://placehold.co/300x400/81ecec/ffffff?text=Midi+Dress",
    sizes: ["S", "M", "L"],
    colors: ["red", "green", "blue"],
    description: "Midi dress yang versatile untuk berbagai occasion",
    stock: 14,
  },
  {
    id: 15,
    name: "Ankle Boots",
    price: 249000,
    originalPrice: 249000,
    category: "shoes",
    image: "https://placehold.co/300x400/636e72/ffffff?text=Ankle+Boots",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["black", "brown"],
    description: "Ankle boots yang stylish dan durable",
    stock: 8,
  },
  {
    id: 16,
    name: "Bucket Hat",
    price: 59000,
    originalPrice: 59000,
    category: "accessories",
    image: "https://placehold.co/300x400/00cec9/ffffff?text=Bucket+Hat",
    sizes: ["all"],
    colors: ["black", "white", "pink"],
    description: "Bucket hat yang trendy untuk summer vibes",
    stock: 35,
  },
  {
    id: 17,
    name: "Cardigan",
    price: 119000,
    originalPrice: 119000,
    category: "tops",
    image: "https://placehold.co/300x400/fab1a0/ffffff?text=Cardigan",
    sizes: ["S", "M", "L"],
    colors: ["white", "brown", "pink"],
    description: "Cardigan yang cozy dan feminine",
    stock: 20,
  },
  {
    id: 18,
    name: "Cargo Pants",
    price: 149000,
    originalPrice: 149000,
    category: "bottoms",
    image: "https://placehold.co/300x400/2d3436/ffffff?text=Cargo+Pants",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "green", "brown"],
    description: "Cargo pants yang utility dan fashionable",
    stock: 11,
  },
  {
    id: 19,
    name: "Slip Dress",
    price: 139000,
    originalPrice: 139000,
    category: "dresses",
    image: "https://placehold.co/300x400/a29bfe/ffffff?text=Slip+Dress",
    sizes: ["XS", "S", "M", "L"],
    colors: ["black", "white", "red"],
    description: "Slip dress yang minimalis dan chic",
    stock: 17,
  },
  {
    id: 20,
    name: "Platform Sandals",
    price: 199000,
    originalPrice: 199000,
    category: "shoes",
    image: "https://placehold.co/300x400/fd79a8/ffffff?text=Platform+Sandals",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["black", "white", "brown"],
    description: "Platform sandals yang trendy dan comfortable",
    stock: 13,
  },
];
